# Generated by Django 4.0.6 on 2022-07-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=100)),
                ('movie_desc', models.TextField()),
                ('launch_date', models.DateField()),
                ('complexity_score', models.IntegerField()),
                ('popularity_score', models.FloatField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
