# Generated by Django 4.0.6 on 2022-07-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['movie_id']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='added',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='edited',
        ),
    ]
